In [3]:
#1
import numpy as np
marks=np.array([78,85,91,67,88])
print(marks)
print(marks.dtype)
print(marks.shape)

[78 85 91 67 88]
int32
(5,)


In [4]:
#2
prices=[120,450,780,220,560]
prices1=np.array(prices)
print(prices1)
print(prices1.ndim)
print(prices1.size)

[120 450 780 220 560]
1
5


In [6]:
#3
players_scores=[20,30,23,10,49,25,69,40,59,60]
players_scores1=np.array(players_scores)
print(players_scores1.shape)
print(players_scores1.size)
print(players_scores1.dtype)
print(players_scores1.ndim)

(10,)
10
int32
1


In [10]:
#4
salary=[25000,30000,45000,28000]
salary1=[]
for num in salary:
    salary1.append(num+5000)
print("using list:",salary1)
salary2=np.array(salary)
salary3=salary2+5000
print("using numpy:",salary3)

using list: [30000, 35000, 50000, 33000]
using numpy: [30000 35000 50000 33000]


In [11]:
#5
marks=[60,59,70,39,40]
marks1=[]
for mark in marks:
    marks1.append(mark+5)
print("using lists:",marks1)
marks2=np.array(marks)
print("using numpy:",marks2+5)

using lists: [65, 64, 75, 44, 45]
using numpy: [65 64 75 44 45]


In [12]:
#6
import numpy as np
import time
list=[39,20,48]
start=time.time()
list1=[x*10 for x in list]
end=time.time()
print("list:",end-start)
start=time.time()
list2=np.array(list)+10
end=time.time()
print("numpy:",end-start)

list: 0.0010657310485839844
numpy: 0.0003108978271484375


In [14]:
#7
prices=[150,200,250,350]
p1=[]
for price in prices:
    p1.append(price*2)
print("list uses loop",p1)
p2=np.array(prices)*2
print("numpy access element directly",p2)

list uses loop [300, 400, 500, 700]
numpy access element directly [300 400 500 700]


In [15]:
#8
stocks=[15,20,25,35]
s1=[]
for x in stocks:
    s1.append(x*2)
print("list uses loop",s1)
s2=np.array(stocks)*2
print("numpy access element directly",s2)

list uses loop [30, 40, 50, 70]
numpy access element directly [30 40 50 70]


In [20]:
#9
expenses=[2000,30040,5000,4990]
sum=0
for x in expenses:
    sum+=x

e2=np.array(expenses).sum()

print("using numpy is easier")

42030
42030
using numpy is easier


In [21]:
#10
marks=np.array([55,65,75,85,95])
print("first element:",marks[0])
print("last element:",marks[-1])
print("third element:",marks[2])

first element: 55
last element: 95
third element: 75


In [24]:
#11
sales=np.array([120,130,140,150,160,170])
print("first three values:",sales[:3])
print("last two values:",sales[-2:])
print("middle values:",sales[2:4])

first three values: [120 130 140]
last two values: [160 170]
middle values: [140 150]


In [28]:
#12
matrix=np.array([[3,4,5],[1,2,8],[6,7,9]])
print(matrix[0])
print(matrix[1])
print(matrix[2])

[3 4 5]
[1 2 8]
[6 7 9]


In [30]:
#13
marks=np.array([35,55,72,89,40,91])
m1=marks>40
print(m1)

[False  True  True  True False  True]


In [31]:
#14
salary=np.array([30000,58000,90000,39000,50200])
s1=salary[salary>50000]
print(s1)

[58000 90000 50200]


In [32]:
#15
temp=np.array([40,50,20,10,34])
t1=temp[temp>30]
print(t1)

[40 50 34]


In [33]:
#16
ratings=np.array([2,5,4,3,5,1])
print(ratings[[0,2,5]])

[2 4 1]


In [34]:
#17
books = np.array(["Python", "Java", "C", "C++", "SQL", "HTML"])
print(books[[1,3,5]])

['Java' 'C++' 'HTML']


In [35]:
#18
scores=np.array([20,20,49,50,0,39,49])
print(scores[[0,3,6]])

[20 50 49]


In [40]:
#19
a=np.array([1,2,3])
b=np.array([4,5,6])
print("addition:",np.add(a,b))
print("subtraction:",np.subtract(a,b))
print("multiplication:",np.multiply(a,b))
print("division:",np.divide(a,b))

addition: [5 7 9]
subtraction: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]


In [42]:
#20
print(np.sqrt(a))
print(np.square(a))
print(np.exp(a))

[1.         1.41421356 1.73205081]
[1 4 9]
[ 2.71828183  7.3890561  20.08553692]


In [43]:
#21
print(np.sin(b))
print(np.cos(b))
print(np.tan(b))

[-0.7568025  -0.95892427 -0.2794155 ]
[-0.65364362  0.28366219  0.96017029]
[ 1.15782128 -3.38051501 -0.29100619]


In [46]:
#22
marks = np.array([78,85,91,67,88])
print(np.mean(marks))
print(np.median(marks))
print(np.sum(marks))
print(np.min(marks))
print(np.max(marks))

81.8
85.0
409
67
91


In [47]:
#23
production = np.array([120,150,130,170,160,180])
print(np.std(production))
print(np.var(production))
print(np.mean(production))

21.147629234082533
447.2222222222222
151.66666666666666


In [48]:
#24
sales = np.array([25000,27000,30000,28000,35000])
print(np.sum(sales))
print(np.mean(sales))
print(np.max(sales))
print(np.min(sales))
print(np.std(sales))
print(np.var(sales))

145000
29000.0
35000
25000
3405.87727318528
11600000.0


In [49]:
#25
scores=np.array([20,20,49,50,0,39,49])
print(np.argmax(scores))
print(np.argmin(scores))

3
4


In [53]:
#26
savings = np.array([100,200,300,400])
print(np.cumsum(scores))
print(np.cumprod(scores))

[ 20  40  89 139 139 178 227]
[    20    400  19600 980000      0      0      0]


In [54]:
#27
health = np.array([True,True,False,True])
print(np.all(True))
print(np.any(True))

True
True
